default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer

  # - repo: local
  #   hooks:
    # - entry: black
    #   id: black
    #   name: black
    #   language: system
    #   pass_filenames: true
    #   types:
    #     - python

    # - id: isort
    #   entry: isort
    #   name: isort
    #   language: system
    #   pass_filenames: true
    #   types:
    #     - python

# Implement this with the new tests
    # - id: vulture
    #   name: vulture
    #   entry: vulture
    #   language: system
    #   files: "src/"
    #   description: Find unused Python code.
    #   pass_filenames: true
    #   types:
    #     - python

# - id: ruff-format
    #   name: ruff-format
    #   entry: ruff format
    #   exclude: "docs/|migrations/.*|literev/urls.py" # exclude test dir
    #   language: system
    #   pass_filenames: true
    #   types:
    #     - python

    # - id: ruff-linter
    #   name: ruff-linter
    #   entry: ruff check
    #   language: system
    #   exclude: "docs/|migrations/.*|literev/urls.py"
    #   pass_filenames: true
    #   types:
    #     - python
