name: fqlearn
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python 3.10
  - poetry
  - pytest
  - isort
  - pre-commit
  - pip
  - mkdocs
  - mkdocs-material
    #- pip:
    # - makim==1.8.2
    
